server:
  port: 8094
  
spring:
  application:
    name: employee-producer
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true